import React, { useState, useEffect } from 'react';
import { FileText, X, Printer, Loader2, Hospital } from 'lucide-react';

const DoctorBriefing = ({ isOpen, onClose, patientData }) => {
  const [brief, setBrief] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (isOpen && patientData) {
      generateBrief();
    }
  }, [isOpen]);

  const generateBrief = async () => {
    setIsLoading(true);
    setError('');
    
    try {
      const response = await fetch('http://localhost:5000/api/generate-brief', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ patientData: patientData.entries.slice(-30) }) // Send last 30 days
      });
      
      if (!response.ok) throw new Error('Failed to fetch brief');
      
      const data = await response.json();
      setBrief(data.brief);
    } catch (err) {
      setError('Unable to generate the medical memo at this time.');
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/60 backdrop-blur-sm fade-in print:bg-white print:p-0 print:block">
      <div className="bg-white rounded-3xl shadow-2xl w-full max-w-2xl overflow-hidden print:shadow-none print:rounded-none border border-gray-100">
        
        {/* Header - Hidden on print, custom print header below */}
        <div className="flex justify-between items-center p-6 border-b border-gray-100 print:hidden">
          <div className="flex items-center space-x-3">
            <div className="bg-primary-light p-2 rounded-xl">
              <FileText className="w-6 h-6 text-primary-dark" />
            </div>
            <h2 className="text-xl font-bold text-gray-800">Clinical Memo</h2>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition-colors">
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-8 print:p-10">
          
          {/* Print Only Header */}
          <div className="hidden print:flex justify-between items-end border-b-2 border-gray-800 pb-4 mb-8">
            <div className="flex items-center space-x-2">
              <Hospital className="w-8 h-8 text-gray-800" />
              <h1 className="text-2xl font-black text-gray-900 tracking-tight">MATRACARE CLINIC</h1>
            </div>
            <div className="text-right text-sm text-gray-600">
              <p>Date: {new Date().toLocaleDateString()}</p>
              <p>Confidential Medical Record</p>
            </div>
          </div>

          <div className="mb-6 pb-6 border-b border-gray-100 print:border-gray-300">
            <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-2">Patient Details</h3>
            <p className="text-lg font-medium text-gray-800">Review Period: Last 30 Days</p>
          </div>

          <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4">AI Diagnostic Brief</h3>
          
          {isLoading ? (
            <div className="flex flex-col items-center justify-center py-12">
              <Loader2 className="w-10 h-10 text-primary-dark animate-spin mb-4" />
              <p className="text-gray-500 font-medium animate-pulse">Consulting Gemini AI...</p>
            </div>
          ) : error ? (
            <div className="bg-danger/10 text-danger-700 p-4 rounded-xl border border-danger/20 font-medium">
              {error}
            </div>
          ) : (
            <div className="prose max-w-none">
              <p className="text-gray-800 leading-relaxed font-medium text-lg whitespace-pre-wrap">
                {brief}
              </p>
            </div>
          )}

          {/* Print Only Footer */}
          <div className="hidden print:block mt-16 pt-8 border-t border-gray-300 text-sm text-gray-500 text-center">
            <p>Generated by MatraCare AI Assistant • For Professional Clinical Use Only</p>
          </div>
        </div>

        {/* Footer Actions - Hidden on print */}
        <div className="bg-gray-50 p-6 flex justify-end space-x-4 border-t border-gray-100 print:hidden">
          <button 
            onClick={onClose}
            className="px-6 py-2.5 rounded-full font-bold text-gray-600 hover:bg-gray-200 transition-colors"
          >
            Close
          </button>
          <button 
            onClick={handlePrint}
            disabled={isLoading || !brief}
            className="flex items-center space-x-2 px-6 py-2.5 rounded-full font-bold text-white bg-primary-dark hover:bg-primary-dark/90 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-md"
          >
            <Printer className="w-5 h-5" />
            <span>Print to PDF</span>
          </button>
        </div>

      </div>
    </div>
  );
};

export default DoctorBriefing;
